<!DOCTYPE html>
<html lang="ja-JP">
<head>
<!-- Global Site Tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-620926-3"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments)};
  gtag('js', new Date());

  gtag('config', 'UA-620926-3');
</script>

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="../style.css">
<link rel="stylesheet" href="../syntax-highlight.css">
<link rel="icon" type="image/png" href="../rurema.png">

<link rel="canonical" href="https://docs.ruby-lang.org/ja/latest/class/LocalJumpError.html">

<title>class LocalJumpError (Ruby 3.4 リファレンスマニュアル)</title>
<meta name="description" content="ある [[c:Proc]] オブジェクトの作成元スコープがすでに終了しているとき、
その [[c:Proc]] オブジェクト内で
return, break, retry のいずれかを実行すると発生します。">
<script src="../script.js"></script>
</head>
<body>


<script type="application/ld+json">
{"@context":"http://schema.org","@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","item":"https://docs.ruby-lang.org/ja/latest/doc/index.html","name":"Ruby 3.4 リファレンスマニュアル","position":1},{"@type":"ListItem","item":"https://docs.ruby-lang.org/ja/latest/library/index.html","name":"ライブラリ一覧","position":2},{"@type":"ListItem","item":"https://docs.ruby-lang.org/ja/latest/library/_builtin.html","name":"組み込みライブラリ","position":3},{"@type":"ListItem","item":"https://docs.ruby-lang.org/ja/latest/class/LocalJumpError.html","name":"LocalJumpErrorクラス","position":4}]}
</script>

<header>
  <nav>
    <ol class="inline-breadcrumb-list">
      <li>
        <a href="../doc/index.html">Ruby 3.4 リファレンスマニュアル</a>
      </li>
      <li>
        <a href="../library/index.html">ライブラリ一覧</a>
      </li>
      <li>
        <a href="../library/_builtin.html">組み込みライブラリ</a>
      </li>
      <li>
        LocalJumpErrorクラス
      </li>
    </ol>
  </nav>

<h1>class LocalJumpError</h1><span class="permalink">[<a href="https://github.com/rurema/doctree/edit/master/refm/api/src/_builtin/LocalJumpError#L1">edit</a>]</span>

</header>

<main>



  <nav>
    クラス・モジュールの継承リスト:
    <ol class="inline-ancestors-list">
      
        <li>
          <a href="../class/BasicObject.html">BasicObject</a>
        </li>
        
      
        <li>
          <a href="../class/Kernel.html">Kernel</a>
        </li>
        
      
        <li>
          <a href="../class/Object.html">Object</a>
        </li>
        
      
        <li>
          <a href="../class/Exception.html">Exception</a>
        </li>
        
      
        <li>
          <a href="../class/StandardError.html">StandardError</a>
        </li>
        
      
      <li>
        LocalJumpError
      </li>
    </ol>
  </nav>











<h2>要約</h2>
<p>
ある <a href="../class/Proc.html">Proc</a> オブジェクトの作成元スコープがすでに終了しているとき、その <a href="../class/Proc.html">Proc</a> オブジェクト内で
return, break, retry のいずれかを実行すると発生します。
</p>
<p>
<a href="../class/Proc.html">Proc</a> の例を参照してください。
</p>



<h2>目次</h2>
<dl>

<dt>インスタンスメソッド</dt>
<dd>
<ul class="class-toc">

<li><a href="#I_EXIT_VALUE">exit_value</a></li>

<li><a href="#I_REASON">reason</a></li>

</ul>
</dd>

</dl>




  <h2>継承しているメソッド</h2>
<dl>
  
<dt>Exceptionから継承しているメソッド</dt>
<dd>
  <ul class="class-toc">
    
      <li><a href="../method/Exception/i/=3d=3d.html">==</a></li>
      
    
      <li><a href="../method/Exception/i/backtrace.html">backtrace</a></li>
      
    
      <li><a href="../method/Exception/i/backtrace_locations.html">backtrace_locations</a></li>
      
    
      <li><a href="../method/Exception/i/cause.html">cause</a></li>
      
    
      <li><a href="../method/Exception/i/exception.html">exception</a></li>
      
    
      <li><a href="../method/Exception/i/full_message.html">full_message</a></li>
      
    
      <li><a href="../method/Exception/i/inspect.html">inspect</a></li>
      
    
      <li><a href="../method/Exception/i/message.html">message</a></li>
      
    
      <li><a href="../method/Exception/i/set_backtrace.html">set_backtrace</a></li>
      
    
      <li><a href="../method/Exception/i/message.html">to_s</a></li>
      
    
  </ul>
</dd>

</dl>


<h2>インスタンスメソッド</h2>
<dl>

<dt class="method-heading" id="I_EXIT_VALUE"><code>exit_value -&gt; object</code><span class="permalink">[<a href="../method/LocalJumpError/i/exit_value.html">permalink</a>][<a href="https://docs.ruby-lang.org/en/3.4/LocalJumpError.html#method-i-exit_value">rdoc</a>][<a href="https://github.com/rurema/doctree/edit/master/refm/api/src/_builtin/LocalJumpError#L11">edit</a>]</span></dt>
<dd class="method-description">
<p>
例外 LocalJumpError を発生する原因となった
break や return に渡した値を返します。
</p>
<p>
例:
</p>
<pre>
def foo
  proc { return 10 }
end

begin
  foo.call
rescue LocalJumpError =&gt; err
  p err              # =&gt; #&lt;LocalJumpError: return from block-closure&gt;
  p err.reason       # =&gt; :return
  p err.exit_value   # =&gt; 10
end

begin
  Block.new { break 5 }.call
rescue LocalJumpError =&gt; err
  p err              # =&gt; #&lt;LocalJumpError: break from block-closure&gt;
  p err.reason       # =&gt; :break
  p err.exit_value   # =&gt; 5
end
</pre>
</dd>


<dt class="method-heading" id="I_REASON"><code>reason -&gt; Symbol</code><span class="permalink">[<a href="../method/LocalJumpError/i/reason.html">permalink</a>][<a href="https://docs.ruby-lang.org/en/3.4/LocalJumpError.html#method-i-reason">rdoc</a>][<a href="https://github.com/rurema/doctree/edit/master/refm/api/src/_builtin/LocalJumpError#L38">edit</a>]</span></dt>
<dd class="method-description">
<p>
例外を発生させた原因をシンボルで返します。
</p>
<p>
返す値は以下のいずれかです。
</p>
<ul>
<li>:break</li>
<li>:redo</li>
<li>:retry</li>
<li>:next</li>
<li>:return</li>
<li>:noreason</li>
</ul>
<p>
例:
</p>
<pre>
def foo
  proc { return 10 }
end

begin
  foo.call
rescue LocalJumpError =&gt; err
  p err              # =&gt; #&lt;LocalJumpError: return from block-closure&gt;
  p err.reason       # =&gt; :return
  p err.exit_value   # =&gt; 10
end

begin
  Block.new { break 5 }.call
rescue LocalJumpError =&gt; err
  p err              # =&gt; #&lt;LocalJumpError: break from block-closure&gt;
  p err.reason       # =&gt; :break
  p err.exit_value   # =&gt; 5
end
</pre>
</dd>


</dl>

</main>

<footer id="footer">
  <a rel="license" href="https://creativecommons.org/licenses/by/3.0/">
    <img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/3.0/88x31.png" />
  </a>

  <a href="https://github.com/rurema/doctree/issues/new" id="feedback-link">フィードバックを送る</a>
  
    / <a href="https://github.com/rurema/doctree/edit/master/refm/api/src/_builtin/LocalJumpError#L1">このマニュアルを編集する</a>
  
  <script>if (window.URLSearchParams) { document.getElementById("feedback-link").search = new URLSearchParams({'body': document.location}); }</script>
</footer>
</body>
</html>
