type=class
superclass=Net=ProtoAuthError
included=
extended=
dynamically_included=
dynamically_extended=
library=net.pop
aliases=
aliasof=
source_location=refm/api/src/net/pop.rd:836

POP3 で認証に失敗したときに発生します。
