<!DOCTYPE html>
<html lang="ja-JP">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <meta http-equiv="Content-Language" content="ja-JP">
  <link rel="stylesheet" type="text/css" href="../style.css">
  <link rel="icon" type="image/png" href="../rurema.png">
  <link rel="canonical" href="http://docs.ruby-lang.org/ja/latest/function/rb_rescue.html">
  <title>function rb_rescue (Ruby 1.8.7)</title>
</head>
<body>

<p>
<a href="../doc/index.html">Ruby 1.8.7 リファレンスマニュアル</a>
&gt; <a href="../function/index.html">関数一覧</a>
&gt; rb_rescue

</p>


<h1>function rb_rescue</h1>
<dl class="functionlist">
<dt>
  <code>VALUE rb_rescue(VALUE (*b_proc)(), VALUE data1, VALUE (*r_proc)(), VALUE data2)</code>
</dt>
<dd>
<dd class="function-description">
<p>
まず b_proc(data1) を実行し、その途中で例外が発生したら r_proc(data2) を実行します。
捕捉する例外は <a href="../class/StandardError.html">StandardError</a> のサブクラスだけです。
</p>
</dd>

</dd>
</dl>


<div id="footer">
  <a rel="license" href="http://creativecommons.org/licenses/by/3.0/">
    <img alt="Creative Commons License" style="border-width:0" src="http://i.creativecommons.org/l/by/3.0/88x31.png" />
  </a>
</div>
</body>
</html>
